import Head from 'next/head'
import React from 'react'
import Button from '../components/Button'
import { InputField } from '../components/InputField'

export default function accountRecovery() {
  return (
    <>
      <Head>
        <title>Errand App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-white flex">
        <div className=" w-3/5 h-full hero-banner font-recoletta flex  justify-center items-center font-bold">
          <p className="text-7xl text-white tracking-wider">
            Run Errands, Get Paid
          </p>
        </div>
        <div className="w-2/5 bg-white pt-16 px-20">
          <img src="/fake-logo.svg" alt="" />

          <div className="pt-10">
            <h1 className="font-inter text-2xl font-bold text-black tracking-wide">
              Account Recovery
            </h1>
            <p className="pt-2 text-base">
              Enter your details in order to recover your Account
            </p>

            <div className="pt-10 space-y-8">
              <InputField label="New Password" placeholder="Enter your New Password" />
              <InputField label="Confirm Password" placeholder="Confirm your New Password" />

              <Button
                child="Recovery Password"
                className="w-full bg-[#243763] text-white rounded-lg p-4 text-base"
              />
              {/* <h5 className="text-center text-black">
              Don’t Have an Account? {" "}
                 <span className="font-bold text-[#243763]">Create Account</span>
              </h5> */}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
