/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { useDispatch, useSelector } from 'react-redux'
import { ErrorAlert } from '../components/Alert'
import Button from '../components/Button'
import { InputField } from '../components/InputField'
import Loader from '../components/Loader'
import { RootState } from '../services/store'
import { loginUser } from '../services/users/login'
import { ILogin } from '../types'

export default function Login() {
  const [visible, setVisible] = useState<boolean>(false)
  const dispatch = useDispatch()
  const router = useRouter()
  const { loading, error, data } = useSelector((state: RootState) => state.login)
  
  console.log(">>>>data", error)

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<ILogin>()

  const loginHandler = ({ ...data }: ILogin) => {
    console.log('>>>>>>data', data)
    dispatch(loginUser({ router, ...data }))
  }

  return (
    <>
      <Head>
        <title>B2b Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center my-28 w-full">
        <form onSubmit={handleSubmit(loginHandler)} className="pt-10">
          <div className="flex items-center justify-center">
            {/* <Image
              src="/logo.svg"
              alt="logo"
              width={200}
              height={200}
              className="text-center"
            /> */}
          </div>
          <p className="text-2xl text-center pt-10 font-semibold">
            Welcome back !
          </p>

          {error && <ErrorAlert message={<><p>The username or password is not correct. </p> <p>Did you <span className='text-black'><Link href="/forgot_password">forget your password ?</Link> </span></p></>
          } />}

          <InputField
            register={register}
            name="username"
            type="text"
            className="w-370 mt-7 border-2 border-borderAsh"
            placeholder="Enter your username"
            message="Please enter username"
            errors={errors.username}
            required
          />

          <InputField
            register={register}
            className="w-370 mt-6"
            type={visible ? 'text' : 'password'}
            name="password"
            show={visible ? 'hide' : 'show'}
            placeholder="Enter your password"
            message="Please enter password"
            errors={errors.password}
            onClick={() => setVisible(!visible)}
            required
          />

          <Button
            className="bg-darkGreen mt-12 py-3.5 font-semibold text-white flex items-center  justify-center rounded-lg cursor-pointer w-full"
            type="submit"
            child={loading ? <Loader /> : 'Login'}
          />

          <p className="text-center pt-4  text-lg text-lightAsh ">
            Don't have an account?{' '}
            <span className="text-darkGreen">
              <Link href="/register">Create an account</Link>{' '}
            </span>
          </p>

          <p className="text-darkGreen text-lg text-center pt-3">
            Forget your password ?
          </p>
        </form>
      </div>
    </>
  )
}
