/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import Button from '../components/Button'
import { InputField } from '../components/InputField'
import { ILogin } from '../types'

export default function Register() {
  const [visible, setVisible] = useState<boolean>(false)

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<ILogin>()

  return (
    <>
      <Head>
        <title>Errand App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-white flex">
        <div className=" w-3/5 h-full hero-banner font-recoletta flex  justify-center items-center font-bold">
          <p className="text-7xl text-white tracking-wider">
            Run Errands, Get Paid
          </p>
        </div>
        <div className="w-2/5 bg-white pt-16 px-20">
          <img src="/fake-logo.svg" alt="" />

          <div className="pt-10">
            <h1 className="font-inter text-2xl font-bold text-black tracking-wide">
              Create an Account
            </h1>
            <p className="pt-2 text-base">
              Let’s get started and create a Profile for you
            </p>

            <div className="pt-10 space-y-8">
              <InputField label="First Name" placeholder="Enter First Name" />
              <InputField label="Last Name" placeholder="Enter First Name" />
              <InputField label="Phone Number" placeholder="Enter First Name" />
              <InputField label="Password" placeholder="Enter First Name" />

              <Button
                child="Register"
                className="w-full bg-[#243763] text-white rounded-lg p-4 text-base"
              />
              <h5 className="text-center text-black">
                Already Have an Account?{' '}
                <span className="font-bold text-[#243763]">Login</span>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
