/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import Button from '../components/Button'
import { InputField } from '../components/InputField'
import { ILogin } from '../types'

export default function PasswordRecovery() {
  const [visible, setVisible] = useState<boolean>(false)

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<ILogin>()

  return (
    <>
      <Head>
        <title>Errand App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-white flex">
        <div className=" w-3/5 h-full hero-banner font-recoletta flex  justify-center items-center font-bold">
          <p className="text-7xl text-white tracking-wider">
            Run Errands, Get Paid
          </p>
        </div>
        <div className="w-2/5 bg-white pt-16 px-20">
          <img src="/fake-logo.svg" alt="" />

          <div className="pt-10">
            <h1 className="font-inter text-2xl font-bold text-black tracking-wide">
              Password Recovery
            </h1>
            <p className="pt-2 text-base">
              Enter your details in order to recover your Password
            </p>

            <div className="pt-10 space-y-12">
              <InputField label="Phone Number" placeholder="Enter First Name" />
              <InputField
                label="Security Question"
                placeholder="Enter First Name"
              />
              <InputField
                label="Answer"
                placeholder="Enter Answer"
              />

              <div className='pt-5'>
                <Button
                  child="Recover Password"
                  className="w-full bg-[#243763] text-white rounded-lg p-5 text-base"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
